windwp/nvim-autopairs

README.md, lua/nvim-autopairs.lua
This simplifies configuration, prevents mismatches and simplifies the
code as well.
=> Use a table instead of two arrays to hold pairs

lua/nvim-autopairs.lua
=> add more pairs group on breakline

README.md, lua/nvim-autopairs.lua, tests/pairs_spec.lua
#17 
I'm still unsure with the option name.
=> feat: added ignored_next_char options

lua/nvim-autopairs.lua
This PR adds an option to close triple quotes like requested in several issues. As this in some special cases could provide unwanted results for some peope, I added this as an option that is default turned off. It could probably be done in a smarter way, but I think this would improve on how this is currently handled.
=> fix: support for close triple quotes

README.md
[Similar](https://github.com/hrsh7th/nvim-compe#mappings) to other plugins.
=> Update nvim-compe setup

README.md
This one bugged me for quite a while 😓 
Let's get this merged!
=> Fix: Syntax in readme.md

README.md, lua/nvim-autopairs/conds.lua, tests/nvim-autopairs_spec.lua
=> Add exclude_filetypes

README.md, lua/nvim-autopairs.lua
coq issue: <https://github.com/ms-jpq/coq_nvim/issues/91>
=> allow disabling bs mapping & add coq config example

README.md, lua/nvim-autopairs/fastwrap.lua
Implements the offset feature to fastwrap match to insert bracket before, or at match.
=> Add fastwrap offset ( Fix #128 )

lua/nvim-autopairs/rules/basic.lua
Ref: https://github.com/windwp/nvim-autopairs/pull/143#issuecomment-930783297
=> enable single quote for rust (correctly)

README.md, lua/nvim-autopairs.lua, lua/nvim-autopairs/utils.lua, tests/nvim-autopairs_spec.lua
=> Feat: Add the option mapping <C-h> to deleting a pair

lua/nvim-autopairs/completion/cmp.lua
=> fix(cmp): issue(#202)

lua/nvim-autopairs/ts-conds.lua
In insert mode the node at the cursor is `source_file`, in that case I should not look for the parent.
Fix #226
=> feat(treesitter): add rule to check node on insert mode

README.md, doc/nvim-autopairs.txt, lua/nvim-autopairs.lua, lua/nvim-autopairs/rule.lua, lua/nvim-autopairs/rules/basic.lua
the basic rule will insert `break undo` key seq `Ctrl-G u` by default.
maybe some people like me don't like this.
i add a new option for that basic rule.
=> FEAT: option for some people who want only one history in undo sequnce

lua/nvim-autopairs.lua
Fixed the problem in #267 and rebased commits.
=> fix: reduce unexpected `end_pair_func` executions

lua/nvim-autopairs.lua
Fixes #173 
I see no other issues with this.
=> Remove unneeded buffer number argument

lua/nvim-autopairs/completion/cmp.lua
Same as #302 but for PureScript.
=> fix(cmp) Disable on_confirm_done for PureScript

lua/nvim-autopairs/rules/basic.lua
Please see [here](https://github.com/windwp/nvim-autopairs/issues/300#issuecomment-1356081754)
=> Expose basic bracket

lua/nvim-autopairs/fastwrap.lua
```
Before              Input                                         After
------------------------------------------------------------------------------
[|(foobar)      <M-e> then press $ then l       [|(foobar)]
[|(foobar)      <M-e> then press $ then h      [|(foobar])
(|foo bar        <M-e> then press q then l      (foo )bar     
(|foo bar        <M-e> then press q then h     (foo) bar     
```
=> add manual position capabilities

lua/nvim-autopairs/completion/handlers.lua
=> Remove check for commit_character

lua/nvim-autopairs/utils.lua
=> refactor: use vim.v instead of vim.cmd('let v:...')

README.md
This PR fixes a small typo in README.md file.
=> docs: fix typo in README.md file

lua/nvim-autopairs/rules/basic.lua
Resolves #116 but for php files
=> close tags in php files

lua/nvim-autopairs/rules/basic.lua
Closes #442
Following on from above. Let me know if you need me to make any changes – thanks again.
=> Add astro filetype to basic rules

lua/nvim-autopairs/rules/basic.lua
HTML tag rules are eligible in blade files too!
=> feat(blade): add blade filetype to html tag rule
