README.md

nvim_select_popupmenu_item is no longer a vim.fn function

fix: nvim_select_popupmenu_item

---

README.md

Current implementation sometimes inserts extra characters.
Taken from [this](https://github.com/hrsh7th/nvim-compe/issues/103#issuecomment-771616238) reference by the author of the plugin.

Fix configuration for nvim-compe in README.md

---

lua/nvim-autopairs/rules/basic.lua

I had problems with the triple backtick support as it is only present in markdown filetypes. Using [vimwiki](https://github.com/vimwiki/vimwiki) changes the filetype to `vimwiki`. This PR adds support for that filetype as well.
Do you want me to use the test for markdown for vimwiki files as well?

Support vimwiki filetype in triple backticks

---

lua/nvim-autopairs.lua

Fix typo in `get_rule()`

---

lua/nvim-autopairs/completion/compe.lua

In case pumvisible is true, and there is no item selected, I think we should map <CR> to `npairs.autopairs_cr()` instead of esc, so endwise can work correctly even when completion popup is on

Map Enter if no completion items is selected

---

lua/nvim-autopairs/rules/endwise-ruby.lua

I wrote some endwise rules for Ruby. It's not perfect and it's just based on my daily usage, but I think this one can be a good start.
There's one case I cannot manage to do though. If things like `if condition` is at the beginning of a line, it won't have endwise because it will conflict with inline `if condition`. I have to choose one. I appreciate if you guys have any advice on this.

Add endwise rule for Ruby

---

lua/nvim-autopairs/rules/basic.lua

Properly pair up triple backticks ``` when filetype is rmarkdown or pandoc, similar to #41.
These filetypes are defined via the https://github.com/vim-pandoc/vim-rmarkdown and https://github.com/vim-pandoc/vim-pandoc packages.
Also see #13, #14, and #30

Handle triple backticks for pandoc and rmarkdown

---

lua/nvim-autopairs/rules/basic.lua

R Markdown filetype is recognized as `rmd` by (Neo)Vim by default and only recognized as `rmarkdown` if there's a supporting plugin. This extends rules from #119 that would apply to `rmarkdown` to `rmd` as well

Apply triple backticks rule to `rmd` filetypes

---

README.md
lua/nvim-autopairs/completion/cmp.lua
lua/nvim-autopairs/completion/compe.lua

Fix #124
This allows to change the auto-insertion character after a function/method is auto-completed, based on filetypes:
```lua
require("nvim-autopairs.completion.compe").setup({
map_cr = true, --  map <CR> on insert mode
map_complete = true, -- it will auto insert `(` (map_char) after select function or method item
map_char = {
tex = "{",
js = "[", -- This is incorrect, but you can change it
},
})
```

Added option to modify map_complete auto-insertion

---

lua/nvim-autopairs/completion/cmp.lua

This code causes an error when `opt` is `nil`, that is when setup like `require("nvim-autopairs.completion.cmp").setup()`.
This pull request fixes this by initializing to an empty table when `opt` is `nil`.
https://github.com/windwp/nvim-autopairs/blob/9d76310855e739f6002d1753aa29bf2fe808e287/lua/nvim-autopairs/completion/cmp.lua#L7-L12

Initialize table when opt is nil

---

README.md
lua/nvim-autopairs/completion/cmp.lua

This allows to change the [confirm behavior of nvim-cmp](https://github.com/hrsh7th/nvim-cmp/blob/main/README.md#cmpconfirm-select--boolean-behavior--cmpconfirmbehaviorinsertreplace-) of the confirm function of nvim-cmp.
By default, Replace is used, if `insert = true` is set, this will use the Insert behavior : 
require("nvim-autopairs.completion.cmp").setup{
map_cr = true,
map_complete = true,
auto_select = true,
insert = true,
}

Add option to allow setup nvim-cmp confirm behavior

---

README.md

When no item in the popup menu is selected, the intended behavior of `<CR>` should be cancelling the completion and triggering auto pairs CR, so it is fine to use `<c-e>` to close the popup menu.

doc: a small change in coq_nvim config example

---

README.md
lua/nvim-autopairs/completion/cmp.lua

closes #175
- opt 1: through appending/redfining 'nvim-autopairs.completion.cmp'.lisp?
- opt 2: pass extra lisp filetypes in on confirm function?

feat(cmp): wrap lisp functions instead of appending paran

---

lua/nvim-autopairs/rules/endwise-elixir.lua

Appends `end` in the following cases:
```elixir
fn (foo) ->
...
end
```
https://hexdocs.pm/elixir/1.12/Enum.html#chunk_while/4-examples
/cc @micke

Add endwise support for inline anonymous functions in Elixir

---

lua/nvim-autopairs.lua

Ref <https://github.com/neovim/neovim/pull/16745>

fix: use 0 instead of nil for current buffer

---

lua/nvim-autopairs/rule.lua

Current default `map_cr` implementation utilizes `<C-o>` to execute `O` in normal mode and then return to insert mode. However, according to [`:h InsertLeave`](https://neovim.io/doc/user/autocmd.html#InsertLeave), `<C-o>` will trigger the `InsertLeave` autocmd, which introduces various other side effects. In my case:
- `InsertLeave` triggers auto save, then `BufWrite`;
- `BufWrite` triggers lsp formatting and editorconfig.
An insert mode `<CR>` operation should not trigger such things. Therefore I propose to replace `<C-o>O` with `<C-c>O`, which could achieve the same results without triggering `InsertLeave` autocmd.

fix: do not trigger `InsertLeave` when `<CR>`

---

lua/nvim-autopairs/completion/cmp.lua

Don't add () when autocompleting import of functions

---

lua/nvim-autopairs/completion/cmp.lua

When commiting a function completion using the '(' character in cmp you
end up with two pairs of parentheses instead of one.
nvim-cmp has just merged a PR (https://github.com/hrsh7th/nvim-cmp/pull/782) that sends the `commit_character` via the
`confirm_done` event.
This commit uses this information to avoid adding a second pair of
parentheses when the user has alredy typed one.

Fixed double parentheses bug when using nvim-cmp

---

lua/nvim-autopairs/completion/cmp.lua
lua/nvim-autopairs/completion/compe.lua

I discovered a potential issue when enabling auto-pairs on completion while using elixir-ls.  Elixir-ls has two different ways to auto-complete functions, because it has both regular method calls (e.g, `String.length()`) as well as method references (e.g. `&String.length/1`).
What I found was, elixir-ls is trying to be smart about which way you are using a function when providing a completion.  In doing so, it always provides an `insertText` with an `insertTextFormat` set to `Snippet`.  It basically does the following:
When completing `String.length()`, it auto-adds the parentheses already, and places the cursor between them (essentially doing what auto-pairs already does).  The pattern looks something like `String.length($1)$0`.
When completing `&String.length/1`, it completes to that …

Prevent auto-pairing on completion, when completion item is a Snippet

---

lua/nvim-autopairs/rules/basic.lua

Used for [raw strings](https://kotlinlang.org/docs/basic-types.html#string-literals).

Enable triple quote in kotlin

---

lua/nvim-autopairs/completion/cmp.lua

The existence of this causes sumneko_lua to think that the call to `cmp.setup()` requires 0 arguments.
Additionally, it allows for going to the correct definition, instead of the one defined in `nvim-autopairs.completion.cmp`.

Remove deprecated setup() function.

---

lua/nvim-autopairs.lua
tests/nvim-autopairs_spec.lua

This PR fixes an issue when expanding an endwise rule, the rules' custom end pair (using `replace_endpair`) was not used - but the rules' original end pair was.
Originally, I was trying to implement a rule that works like [vim-closer](https://github.com/rstacruz/vim-closer). It tries to close all of the opened pairs in that line when pressing `<CR>`.
The following gist implements a rule that acts like vim-closer, described above: 
https://gist.github.com/yardnsm/3818a56526d3d56343b00a03aa2b0269
Input:
```javascript
(function () { |
```
After pressing `<CR>`:
```javascript
(function () {
|
})
```

Use replace_endpair when expanding with endwise

---

README.md
lua/nvim-autopairs/completion/cmp.lua
lua/nvim-autopairs/completion/handlers.lua

This PR is a proposal to rewrite `on_confirm_done`
This PR adds some defaults:
- Each filetype has a setting
- A check based on the `kind` of autocomplete
- A `handler` function on `on_confirm_done`
The idea is that the user handles each filetype.
```lua
M.filetypes = {
-- Alias to all filetype
["*"] = {
["("] = {
kind = {
cmp.lsp.CompletionItemKind.Function,
cmp.lsp.CompletionItemKind.Method,
},
handler = function(char, item, bufnr) end
}
}
}
```
`kind` determines which `cmp` return types from autocomplete are valid for adding `(`

Proposal: rewrite `cmp.on_confirm_done`

---

lua/nvim-autopairs/completion/cmp.lua
lua/nvim-autopairs/completion/handlers.lua

The `on_confirm_done` event from nvim-cmp sends us which character was used to commit the completion via the `commit_character` entry.
This PR:
* Passes the `commit_character` as the last parameter to the `*` handler.
* Modifies the `*` handler to check if `commit_character` is equal to the trigger character `char`. If they are equal it skips adding another pair.

Use `commit_character` from nvim-cmp event to avoid adding double parenthesis

---

lua/nvim-autopairs.lua

Pass `col` and `rule` to the `:with_del` callback so it matches the other `:with_*` callbacks.

Pass column and rule information to `:with_del` callback

---

lua/nvim-autopairs/rules/basic.lua

Python allows for tripple quotes to be `'''`.

python triple single quotes pair

---

lua/nvim-autopairs.lua

When using the mapping for `<BS>` in README:
```lua
MUtils.BS = function()
if vim.fn.pumvisible() ~= 0 and vim.fn.complete_info({ 'mode' }).mode == 'eval' then
return npairs.esc('<c-e>') .. npairs.autopairs_bs()
else
return npairs.autopairs_bs()
end
end
remap('i', '<bs>', 'v:lua.MUtils.BS()', { expr = true, noremap = true })
```
no `bufnr` is passed to `autopairs_bs()` thus the default value would be `0`, and in this condition, the result of 
```lua
local rules = M.get_buf_rules(bufnr)
```
will be an empty table.

Fix empty rules when bufnr is 0

---

lua/nvim-autopairs/fastwrap.lua

As mentionned in this issue: #247  
When a character matches at the end of the line, it overwrites the end key match and uses the end key symbol:
```lua
if i == str_length then
is_end_key = false
key = config.end_key
offset = 0
end
```
This means, if you have a matching character at the end of the line (such as a semicolon), fastwrap will put the closing pair after the match instead of before it, which often isn't what you want:
```
Before       Fastwrap    Input    After
-------------------------------------------
(|)word;     (|)word$    $        (word;)
```
This PR removes this behavior and makes an end match like any other match:
```
Before       Fastwrap     Input    After
-------------------------------------------
(|)word;     (|)wordq$    q        (word);
(|)word;     (|)wordq$ …
```

Fix: fastwrap over end-line characters

---

lua/nvim-autopairs/completion/cmp.lua

As Haskell does not use round brackets for function parameters on_confirm_done should be disabled for this filetype.
Thanks for the cool plugin :D

fix(cmp): Disable on_confirm_done for haskell

---

README.md
lua/nvim-autopairs/completion/cmp.lua
lua/nvim-autopairs/completion/handlers.lua

During #244, the check of rules was removed. Using only `vim.api.nvim_feedkeys`.
The check must be done because it is not done in the same way as the insertion. It is done after completion, before insert `(`
**JavaScript Example**: Add after completion `()` only if not in `import_statement` or `named_imports` node.
```lua
cmp.event:on('confirm_done', cmp_autopairs.on_confirm_done())
Rule(
'(',
')',
{ 'javascript', 'typescript', 'javascriptreact', 'typescriptreact' }
):with_pair(ts_conds.is_in_range(function(param)
if not param then
return false
end
return not vim.tbl_contains(
{ 'named_imports', 'import_statement' },
param.type
)
end, function()
local cursor = vim.api.nvim_win_get_cursor(0)
return { cursor[1] - 1, cursor[2] }
end)),
``` …

Fix `on_confirm_done`

---

lua/nvim-autopairs/rule.lua

This allows configs to manipulate the Rule table, which can be used to override functions, make custom aliases, ...
`Rule.__index = Rule` was actually useless as `Rule` is never set as a metatable on rule instances.
Setting `Rule` as rule instances metadata would actually make `__call` work in too many cases like `my_rule(...)` which doesn't mean anything.
---
For example in my configs I want to use more readable function names instead of `with_*`, like so:
```lua
local Rule = require"nvim-autopairs.rule"
local cond = require"nvim-autopairs.conds"
Rule.insert_pair_when = Rule.with_pair
Rule.cr_expands_pair_when = Rule.with_cr
Rule.bs_deletes_pair_when = Rule.with_del
Rule.just_move_right_when = Rule.with_move
cond.never = cond.none()
cond.always = cond.done()
```

Return Rule table not Rule.new function

---

README.md
doc/nvim-autopairs.txt
lua/nvim-autopairs/fastwrap.lua

`%)` was actually present twice!
---
This fast wrap system is REALLY COOL :heart: 
Also I think `fast_wrap.*` options would really benefit from being documented!
(I also have few ideas of things to add there, will probably make issues/PR at some point)

Remove duplicated %) in fast_wrap.pattern

---

lua/nvim-autopairs/ts-conds.lua

ts_utils.is_in_node_range is now deprecated (as get_node_range)
see: https://github.com/nvim-treesitter/nvim-treesitter/pull/4300

fix deprecated ts_utils is_in_node_range

---

lua/nvim-autopairs/utils.lua

I wanted to re-use `nvim-autopairs.rules.basic.bracket_creator()` to make some patterns for myself for Rust (e.g. `Vec<u32>` and `<T: AsRef<String>>` but noticed that `utils.is_bracket()` and `.is_close_bracket()` didn't list angled brackets so I added them. 
Perhaps this could be useful for others as well :)

Recognize angle brackets (<>) as brackets in util functions

---

README.md

Looking at [the source code](https://github.com/windwp/nvim-autopairs/blob/6a5faeabdbcc86cfbf1561ae430a451a72126e81/lua/nvim-autopairs.lua#L19), it seems that the default value for the `disable_filetype` option is `{ "TelescopePrompt", "spectre_panel" }`.
I updated the README.md with this correct value.

README: update default value for disable_filetype option

---

lua/nvim-autopairs.lua

When `BufDelete` is triggered after closing a floating window such as one from `vim-floaterm`, the `bufnr` the event gets is that of the file you're editing, not the buffer for the terminal, which is causing this autocommand to clear the rules for the current file.
Making sure the buffer we're clearing rules for isn't the buffer we're currently on fixes the issue for me, and seems to make sense because I would imagine the buffer we're currently looking at isn't the buffer that we just deleted and thus triggered a `BufDelete` event.
This should also fix https://github.com/windwp/nvim-autopairs/issues/293 as it seems to be the same issue.

fix: don't clear rules after closing floating win

---

lua/nvim-autopairs.lua
tests/nvim-autopairs_spec.lua

The issue was that when checking if we should move right, the current char was never checked to be valid for the current rule.
Fixes #331
I didn't manage to run the tests locally, this is why I made many commits & used the CI to test :eyes:
~Only 1 test is failing, and I don't understand why, see the comment below~

Do not move right when char is not valid for rule

---

README.md

Added documentation for installing nvim-autopairs with lazy.nvim plugin manager.

docs(plugin): add docs for installing nvim-autopairs with lazy.nvim

---

lua/nvim-autopairs/conds.lua
lua/nvim-autopairs/rules/basic.lua

Problem:
I faced this issue when trying to write a simple rule for a block comment:
```lua
npairs.add_rule(
Rule('/**', '  */')
:with_pair(cond.not_after_regex('.-%*/', -1))
:set_end_pair_length(3)
)
```
This rule kept failing and I thought I was going insane or just dumb but it turns out due to the odd nature of how variables are captured in lua. The first time that the `not_after_regex` function is run it instantiates the function to be returned with the *cached* value of `length`, and this is essentially always going to be the referenced value from within the returned function. I.e.:
```lua
cond.not_after_regex = function(regex, length)
length = length or 1
if not regex then
return cond.none()
end
---@param opts CondOpts
return function(opts)
log.debug('not_after_regex')
if length < 0 …
```

fix: prevent conds lambda from caching the first length parameter

---

lua/nvim-autopairs/conds.lua

Hi thanks for patching things up with the `length` parameter; sorry to bother one last time but I believe there was a small bug in the latest commit that would cause an error saying there was an attempt to perform arithmetic on a nil value. Should be fine with this commit

fix: prevent potential arithmetic operation against nil

---

lua/nvim-autopairs.lua

Fixes the same error as #299 but for ctrl-h and ctrl-w.

fix: remove unneeded buffer number argument(c-w c-h)

---

lua/nvim-autopairs/rules/basic.lua

htmldjango files should also be supported with basic tags.
I think not having a specified table of filetypes for stuff like this is not a good idea, but it works for now.

fix: support htmldjango in basic tag rule

---

README.md
lua/nvim-autopairs/fastwrap.lua

- Custom keymap for the position of endpair instead of the default `h`/`l` for before/after
- Option to position cursor before/after the endpair if uppercase of the `before_key`|`after_key` is pressed
- Redundant code refactor

feat(fastwrap): custom keymap for the position of endpair

---

lua/nvim-autopairs.lua
lua/nvim-autopairs/rule.lua

i made an issue about this #390 but i was bit scared of making a pull request (thought i would break something)
then i tested the plugin at bit with my own fork everything seemed fine so i made this
tl;dr
when pairs expand they draw the cursor twice (for like half a frame)
```
{
|     |
}
```
i made a work around using \<cmd\> as it doesn't trigger a cursor redraw(or switch modes)
but to use normal mode functions i had to use `normal` which does switch modes but doesn't redraw the cursor
i made a version that fully works in insert mode in my own plugin but doesn't indent none {} pairs properly
https://github.com/Sam-programs/autopairs.nvim/blob/main/lua/autopairs.lua#L352
i wasn't able to replicate the == motion perfectly with functions

made the plugin move the cursor less

---

lua/nvim-autopairs.lua
lua/nvim-autopairs/rule.lua

this fixes =,$ and k  mappings being broken (which i made sorry users)
and doesn't move the cursor on custom pairs with a cmd hack
more info:
https://github.com/windwp/nvim-autopairs/pull/394
so yeah here is the new pr with more sane commits windwp
i doubt the test on line 82 of test_utils is gonna pass tho _it's probably safe to remove_

cmd hack to not move the cursor and a fix for recursive mapping

---

lua/nvim-autopairs/completion/cmp.lua
lua/nvim-autopairs/completion/handlers.lua

this just sets funcParensDisabled to false to fixing https://github.com/windwp/nvim-autopairs/issues/388
```lua
M.python = function(char, item, bufnr, rules, _)
item.data.funcParensDisabled = false
M["*"](char,item,bufnr,rules)
end
```

fix(#388) force pairs to work with pyright

---

lua/nvim-autopairs/completion/handlers.lua

well i forgot to check if data is nil sorry about that
checking should fix this
https://github.com/windwp/nvim-autopairs/issues/410

fix Python handler erroring because of writing to a nil table

---

lua/nvim-autopairs/ts-conds.lua
lua/nvim-autopairs/ts-utils.lua
tests/test_utils.lua

try new `vim.treesitter.get_node_text`, falling back to deprecated `vim.treesitter.query.get_node_text`

`vim.treesitter.query.get_node_text()` deprecated

---

lua/nvim-autopairs/ts-conds.lua
lua/nvim-autopairs/ts-utils.lua
tests/endwise/sample.md
tests/test_utils.lua
tests/treesitter_spec.lua

When a rule is defined which calls the `:with_context()` method, has a
specified filetype, and is operating in a buffer with a treesitter
parser attached, the rule will only execute iff the treesitter language
at the cursor matches one of the filetypes specified in the initial rule
definition.
> If there are no specified filetypes, of there is no parser attached to
> the current buffer, the rule executes as normal
---
For the tests, I created a sample.md file which I then use with the rule to test. It was required to make a small modification to `Test_withfile`. We needed to carry out a full parse of the buffer tree which returns a language tree with the injected child trees. The test check if the rules work exclusively in the specified grammars/filetypes.

feat: allow rules to be treesitter context aware (#423)

---

lua/nvim-autopairs/completion/cmp.lua

Since on_confirm_done is disabled for all LaTeX documents (file type 'tex'), it should also be disabled for all other TeX file types. Currently it is still enabled on TeX files (plaintex) and ConTeXt files (context).
This is a little bit irritating for new users, since when start writing a new LaTeX file with the extension '*.tex' it has the type plaintex in the beginning.
See https://neovim.io/doc/user/filetype.html#ft-tex-plugin

Disable on_confirm_done for all TeX file types

---

lua/nvim-autopairs.lua
lua/nvim-autopairs/completion/cmp.lua
lua/nvim-autopairs/completion/compe.lua

fix: avoid global variable usage

---

lua/nvim-autopairs/completion/cmp.lua

Arguments are passed just by appending them after a space, parentheses not used.

fix: don't add parentheses after bash/shell functions

---

lua/nvim-autopairs/conds.lua
tests/nvim-autopairs_spec.lua

opposite direction for length in before_regex() condition

---

lua/nvim-autopairs/completion/cmp.lua

Nix is like Bash, functions are called just with spaces to separate arguments.

fix(nix): don't add parenthesis after functions

---

lua/nvim-autopairs/rules/basic.lua

Adds a rule for `''` which is special in `nix` (there are also no regular single quote strings)

fix(nix): proper multi-line string rule

---

lua/nvim-autopairs/fastwrap.lua

fix: virtual fastwrap highlighting with tabs

---

lua/nvim-autopairs/rules/basic.lua

htmlangular filetype was recently introduced in neovim.
Related PRs:
- https://github.com/neovim/neovim/pull/29633
- https://github.com/neovim/neovim/pull/29646

feat(html): added htmlangular filetype

---

lua/nvim-autopairs/completion/cmp.lua

One more language that does not use () on functions :)

fix(cmp): disable on_confirm_done for helm

---

lua/nvim-autopairs/fastwrap.lua

When window view is shifted, fast wrap virtlines is also shifted, result in inconsistent state. The easiest solution is to restore window col view to 0.
https://github.com/user-attachments/assets/0aab36b6-c33c-4bf1-9089-3833bfad792e

fix(fast-wrap): restore leftcol when it begins to shift text

---

doc/nvim-autopairs.txt
lua/nvim-autopairs/fastwrap.lua

Barely tested
I have no idea how to develop neovim / lua etc, so take it as you will.
Next step would be removing repeating options
```
e.g.        (|abc)))))))
currently:       qwerty$
better:          h     $
```

feat(fast_wrap): add options for direct end_key use

---

lua/nvim-autopairs/fastwrap.lua

vim.highlight is deprecated starting `nvim 0.11`.

♻️refactor(vim.highlight): Deprecation

---

lua/nvim-autopairs/rules/basic.lua

This requests adds support basic rules for eruby filetype which used in Ruby on Rails `erb`  html template files.

Add suport of eruby filetype in basic tag rule

---

README.md

The current default values code block imitates lua but does not consist of valid lua code.
Add the missing commas to this block and reformat it with stylua.

README: make default values valid lua

---

lua/nvim-autopairs/rules/basic.lua

Scala and its build tool sbt also support triple quotes

feat: support triple quotes in Scala

---

lua/nvim-autopairs/rules/basic.lua

Add quarto to the filetypes supported for the triple backticks rules. Quaro is basically an extension to markdown and related to both pandoc and rmarkdown.

feat: add quarto filetype to triple backticks rules

---

README.md
doc/nvim-autopairs.txt
lua/nvim-autopairs.lua

This adds a new configuration option called `enabled` that gives the user more control over when a buffer should be enabled for autopairs. This can be useful for enabling/disabling based on more than just filetype such as buffer type

feat: add an `enabled` configuration function for more control of buffer attachment

---

lua/nvim-autopairs/rules/endwise-ruby.lua

Previously on my PR #79, these 3 scenarios are working:
```ruby
class SomeClass
if flag
end 
...
tmp = if flag
end
return "ok" if flag
```
However, I couldn't handle the case when some of the keywords are at the beginning of a line. Now this PR should do the trick:
```ruby
if flag
end
```

Match keyword when it's at the start of the line

---

lua/nvim-autopairs/rules/basic.lua

HEEx is short for "HTML + Embedded Elixir", the embedded templates used by Elixir's Phoenix framework. You commonly mix HTML alongside Elixir syntax (in parenthesis):
`<h1>{expand_title(@title)}</h1>`
This PR ensures basic autopairs functionality in those files for the HTML tags.

Add Elixir's heex filetype to the list of basic rule filetypes.
